<?php

return [
    /* Admins can replace this list in System Settings > 违禁词管理. */
    'default_forbidden_words' => [
        'Amazon', '亚马逊',
        'eBay', '易贝',
        'AliExpress', '全球速卖通', '速卖通',
        'Alibaba', '阿里巴巴', '阿里巴巴国际站',
        '1688',
        'Taobao', '淘宝',
        'Tmall', '天猫',
        'JD.com', '京东', '京东商城',
        'Pinduoduo', '拼多多',
        'Temu',
        'SHEIN', '希音',
        'Shopee', '虾皮',
        'Lazada', '来赞达',
        'Walmart', '沃尔玛',
        'Etsy',
        'Rakuten', '乐天',
        'Mercado Libre', '美客多',
        'Coupang', '酷澎',
        'Tokopedia',
        'Bukalapak',
        'Flipkart',
        'Daraz',
        'Noon',
        'DHgate', '敦煌网',
        'TikTok Shop',
        'Douyin', '抖音商城',
        'Kuaishou', '快手小店',
        'Xiaohongshu', '小红书',
        'Vipshop', '唯品会',
        'Suning', '苏宁',
        'Gome', '国美',
        'Poizon', '得物',
        'Dangdang', '当当',
    ],
];
